### ISSUE TITLE
Error de Timeout

### ISSUE THREAD

**Issue by gabporres22** [TodoPago/SDK-Java#12]
Aleatoriamente tengo problemas de timeout, tanto con el sdk Java, como con el cliente php.

Sin importar que haga, funciona o no de ratos. Mediante Leandro Avalos, quien me confirma que el estado del servicio esta bien, haciendo la misma prueba a mi me falla. Localmente no tenemos firewall ni proxys.

Sep 05, 2017 10:54:49 AM ar.com.todopago.utils.TodoPagoConectorAuthorize createPayload
INFO: Armando payload: <Request><CURRENCYCODE>032</CURRENCYCODE><ENCODINGMETHOD>XML</ENCODINGMETHOD><MERCHANT>1234_5678</MERCHANT><OPERATIONID>112233</OPERATIONID><AMOUNT>786.46</AMOUNT><URL_ERROR></URL_ERROR><EMAILCLIENTE>gabriel@gmail.com</EMAILCLIENTE><SECURITY>f3d8b72c94ab4a06be2ef7c95490f7d3</SECURITY><URL_OK></URL_OK><CSSTSTREET1>aa</CSSTSTREET1><CSSTCITY>BA</CSSTCITY><CSITPRODUCTSKU>1</CSITPRODUCTSKU><CSSTPHONENUMBER>000000</CSSTPHONENUMBER><CSSTPOSTALCODE>0</CSSTPOSTALCODE><CSBTPOSTALCODE>0</CSBTPOSTALCODE><CSPTGRANDTOTALAMOUNT>0.00</CSPTGRANDTOTALAMOUNT><CSSTFIRSTNAME>Nombre</CSSTFIRSTNAME><CSSTEMAIL>mail@mail.com</CSSTEMAIL><CSBTFIRSTNAME>Nombre</CSBTFIRSTNAME><CSBTCITY>BA</CSBTCITY><CSBTSTREET1>aa</CSBTSTREET1><CSBTLASTNAME>Apellido</CSBTLASTNAME><CSSTSTATE>B</CSSTSTATE><CSBTCOUNTRY>AR</CSBTCOUNTRY><CSSTCOUNTRY>AR</CSSTCOUNTRY><CSITPRODUCTNAME>1</CSITPRODUCTNAME><CSBTPHONENUMBER>000000</CSBTPHONENUMBER><CSSTLASTNAME>Apellido</CSSTLASTNAME><CSITPRODUCTCODE>1</CSITPRODUCTCODE><CSBTCUSTOMERID>0</CSBTCUSTOMERID><CSBTEMAIL>mail@mail.com</CSBTEMAIL><CSPTCURRENCY>ARS</CSPTCURRENCY><CSITTOTALAMOUNT>0.00</CSITTOTALAMOUNT><CSITUNITPRICE>0.00</CSITUNITPRICE><CSBTSTATE>B</CSBTSTATE><CSITPRODUCTDESCRIPTION>1</CSITPRODUCTDESCRIPTION><CSBTIPADDRESS>127.0.0.1</CSBTIPADDRESS><CSITQUANTITY>1</CSITQUANTITY></Request>
Sep 05, 2017 10:54:49 AM ar.com.todopago.utils.TodoPagoConectorAuthorize parseToSendAuthorizeRequest
INFO: Armando SendAuthorizeRequest: ar.com.todopago.api.authorize.SendAuthorizeRequest@174d20a
Exception in thread "main" com.sun.xml.internal.ws.client.ClientTransportException: HTTP transport error: java.net.ConnectException: Operation timed out (Connection timed out)
at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:117)
at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:208)
at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:130)
at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:124)
at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:1121)
at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:1035)
at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:1004)
at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:862)
at com.sun.xml.internal.ws.client.Stub.process(Stub.java:448)
at com.sun.xml.internal.ws.client.sei.SEIStub.doProcess(SEIStub.java:178)
at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:93)
at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
at com.sun.proxy.$Proxy31.sendAuthorizeRequest(Unknown Source)
at ar.com.todopago.utils.TodoPagoConectorAuthorize.getpaymentValues(TodoPagoConectorAuthorize.java:82)
at ar.com.todopago.api.TodoPagoConector.sendAuthorizeRequest(TodoPagoConector.java:133)
at com.ar.todopago.ejemplo.RequestTest.main(RequestTest.java:21)

Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:104)

... 16 more

**Comment by martinstraus** [comment]
¿Esto te está ocurriendo en modo desarrollo o en modo producción? En modo desarrollo, el WSDL tiene URL con IPs que parecen ser privadas, de manera que jamás se podría conectar el SDK.

Por ejemplo, si entrás acá https://developers.todopago.com.ar/services/Authorize?wsdl los bindings tienen direcciones como esta:

    <soap:address location="https://10.123.4.121:8243/services/Authorize.AuthorizeHttpsSoap11Endpoint"/>

La IP 10.123.4.121 no es pública, así es imposible conectarse... Algo no está bien en ese entorno.
